### PR TITLE
Remove tx cannon

### PR DESCRIPTION
**Pull request by vicsn**
The playground page introduced here mostly uses tx-cannon, which is a private repo: https://github.com/ProvableHQ/welcome/pull/338

I started adjusting it, but I'm not aware of:

- whether the badge stuff is outdated
- whether we want to recommend usage of the snarkos developer CLI, https://aleo.tools/develop, or the SDK (which is broken at the moment due to the many recent changes in snarkVM)

### CODE REVIEW

**Comment by vicsn** [comment]
Tagging @d0cd and @onetrickwolf as reviewers

**Comment by onetrickwolf** [comment]
I think I was removed from this repo I can't review but LGTM 👍

**Review by d0cd — APPROVED** [review]

**Comment by d0cd** [comment]
@vicsn The changes look good! Can you resolve the conflicts?

**Comment by vicsn** [comment]
@d0cd Resolved!

**Pull request merged**
